# Generated by Django 4.0.4 on 2022-05-15 20:27

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='lineCode',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='5LRy', editable=False, max_length=22),
        ),
    ]
