# Generated by Django 4.0.4 on 2022-05-16 10:02

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linepay', '0002_alter_line_linecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='linepayuser',
            name='nextInLine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='line',
            name='lineCode',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='3u6P', editable=False, max_length=22),
        ),
    ]
